{"uuid": "ef3dfad8-9689-456d-a88a-856a21b361eb", "children": ["3ecb8a14-9a7c-427f-b19e-c0fffbbd6471", "f0ab4fdd-401b-4fe1-9eb4-6738f95fbdd2", "da863b32-dbb7-4814-8c76-de1026498844"], "befores": [{"name": "init_bid", "status": "broken", "statusDetails": {"message": "AttributeError: 'NoneType' object has no attribute 'is_displayed'\n", "trace": "  File \"C:\\python35\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\python35\\lib\\site-packages\\_pytest\\fixtures.py\", line 937, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\python35\\lib\\site-packages\\_pytest\\fixtures.py\", line 790, in call_fixture_func\n    res = next(it)\n  File \"D:\\Pycharm\\Scripts\\qianchengdai\\Cases\\conftest.py\", line 46, in init_bid\n    home.get_bid_project()\n  File \"D:\\Pycharm\\Scripts\\qianchengdai\\Pages\\home.py\", line 12, in get_bid_project\n    self.wait_click(home_locator.bid_project)\n  File \"D:\\Pycharm\\Scripts\\qianchengdai\\Pages\\basepage.py\", line 35, in wait_click\n    raise e\n  File \"D:\\Pycharm\\Scripts\\qianchengdai\\Pages\\basepage.py\", line 31, in wait_click\n    ele=Wait.until(ec.element_to_be_clickable(locator))\n  File \"C:\\python35\\lib\\site-packages\\selenium\\webdriver\\support\\wait.py\", line 71, in until\n    value = method(self._driver)\n  File \"C:\\python35\\lib\\site-packages\\selenium\\webdriver\\support\\expected_conditions.py\", line 297, in __call__\n    element = visibility_of_element_located(self.locator)(driver)\n  File \"C:\\python35\\lib\\site-packages\\selenium\\webdriver\\support\\expected_conditions.py\", line 128, in __call__\n    return _element_if_visible(_find_element(driver, self.locator))\n  File \"C:\\python35\\lib\\site-packages\\selenium\\webdriver\\support\\expected_conditions.py\", line 148, in _element_if_visible\n    return element if element.is_displayed() == visibility else False\n"}, "start": 1574778850012, "stop": 1574778866185}, {"name": "init_bid", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed\nfrom unknown error: web view not found\n  (Session info: chrome=76.0.3809.132)\n\n", "trace": "  File \"C:\\python35\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\python35\\lib\\site-packages\\_pytest\\fixtures.py\", line 937, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\python35\\lib\\site-packages\\_pytest\\fixtures.py\", line 790, in call_fixture_func\n    res = next(it)\n  File \"D:\\Pycharm\\Scripts\\qianchengdai\\Cases\\conftest.py\", line 44, in init_bid\n    login.register(bid_data.login_data['user_name'], bid_data.login_data['password'])\n  File \"D:\\Pycharm\\Scripts\\qianchengdai\\Pages\\login.py\", line 15, in register\n    self.clear_user_name()\n  File \"D:\\Pycharm\\Scripts\\qianchengdai\\Pages\\login.py\", line 59, in clear_user_name\n    ele=self.get_user_name().clear()\n  File \"D:\\Pycharm\\Scripts\\qianchengdai\\Pages\\login.py\", line 29, in get_user_name\n    user_name=self.wait_ele(login_locator.username)\n  File \"D:\\Pycharm\\Scripts\\qianchengdai\\Pages\\basepage.py\", line 25, in wait_ele\n    raise e\n  File \"D:\\Pycharm\\Scripts\\qianchengdai\\Pages\\basepage.py\", line 20, in wait_ele\n    ele = Wait.until(ec.presence_of_element_located((locator)))\n  File \"C:\\python35\\lib\\site-packages\\selenium\\webdriver\\support\\wait.py\", line 71, in until\n    value = method(self._driver)\n  File \"C:\\python35\\lib\\site-packages\\selenium\\webdriver\\support\\expected_conditions.py\", line 64, in __call__\n    return _find_element(driver, self.locator)\n  File \"C:\\python35\\lib\\site-packages\\selenium\\webdriver\\support\\expected_conditions.py\", line 415, in _find_element\n    raise e\n  File \"C:\\python35\\lib\\site-packages\\selenium\\webdriver\\support\\expected_conditions.py\", line 411, in _find_element\n    return driver.find_element(*by)\n  File \"C:\\python35\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 978, in find_element\n    'value': value})['value']\n  File \"C:\\python35\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\python35\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1574778866539, "stop": 1574778876551}, {"name": "init_bid", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.SessionNotCreatedException: Message: session not created\nfrom chrome not reachable\n  (Session info: chrome=76.0.3809.132)\n\n", "trace": "  File \"C:\\python35\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\python35\\lib\\site-packages\\_pytest\\fixtures.py\", line 937, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\python35\\lib\\site-packages\\_pytest\\fixtures.py\", line 790, in call_fixture_func\n    res = next(it)\n  File \"D:\\Pycharm\\Scripts\\qianchengdai\\Cases\\conftest.py\", line 30, in init_bid\n    driver=Chrome()\n  File \"C:\\python35\\lib\\site-packages\\selenium\\webdriver\\chrome\\webdriver.py\", line 81, in __init__\n    desired_capabilities=desired_capabilities)\n  File \"C:\\python35\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 157, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"C:\\python35\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 252, in start_session\n    response = self.execute(Command.NEW_SESSION, parameters)\n  File \"C:\\python35\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\python35\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1574778876723, "stop": 1574778895974}], "start": 1574778876723, "stop": 1574778896103}