{"name": "test_02_login_alter_error[data0]", "status": "passed", "attachments": [{"name": "log", "source": "6ae87e90-726f-49fd-94bd-ed14559965cc-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "data", "value": "{'Caseid': 4, 'module': '登录', 'title': '错误密码登录', 'username': '18684720553', 'password': '12', 'expect': '帐号或密码错误!'}"}], "start": 1558759847813, "stop": 1558759848401, "uuid": "94ded796-85a1-4c98-8e2f-8a914c172e2a", "historyId": "ea1c0f90cb3f5fd8a050970d58ee5bda", "fullName": "Cases.test_login#test_02_login_alter_error[data0]", "labels": [{"name": "tag", "value": "error"}, {"name": "parentSuite", "value": "Cases"}, {"name": "suite", "value": "test_login"}, {"name": "host", "value": "LAPTOP-VNEUB3U3"}, {"name": "thread", "value": "14360-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Cases.test_login"}]}