{"name": "test_02_login_alter_error[data1]", "status": "passed", "attachments": [{"name": "log", "source": "144483e3-8e8f-4e0c-b7b3-81f2cd396965-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "data", "value": "{'Caseid': 5, 'module': '登录', 'title': '未注册账号登录', 'username': '13541781424', 'password': '123456', 'expect': '此账号没有经过授权，请联系管理员!'}"}], "start": 1558759848408, "stop": 1558759848966, "uuid": "9adf7f40-5ae6-4715-8b00-9596cb4ff10d", "historyId": "d38653b33460b7c16a92db94b238fd2a", "fullName": "Cases.test_login#test_02_login_alter_error[data1]", "labels": [{"name": "tag", "value": "error"}, {"name": "parentSuite", "value": "Cases"}, {"name": "suite", "value": "test_login"}, {"name": "host", "value": "LAPTOP-VNEUB3U3"}, {"name": "thread", "value": "14360-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Cases.test_login"}]}